### ISSUE TITLE
db:migrate fails on CentOS 6 / mysql-server 5.1.73

### ISSUE THREAD

**Issue by bjo81** [idb-project/the-idb#398]
rake db:migrate fails due to an invalid SQL syntax:

```
-- add_column(:machines, :software, :json)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json' at line 1: ALTER TABLE `machines` ADD `software` json
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/opt/the-idb/db/migrate/20161123132943_add_software_to_machines.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1284:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json' at line 1: ALTER TABLE `machines` ADD `software` json
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/opt/the-idb/db/migrate/20161123132943_add_software_to_machines.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1284:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json' at line 1
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.2.4/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:542:in `add_column'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/opt/the-idb/db/migrate/20161123132943_add_software_to_machines.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1284:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by rbns** [comment]
mysql >= 5.7.8 is required for columns of type JSON: https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by bjo81** [comment]
Ok, so I have to put additional sources for the mysql-packages into the install doc for CentOS 6.
